# Generated by Django 4.0.1 on 2023-03-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0004_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField()),
                ('message_reply', models.TextField(null=True)),
                ('pic', models.ImageField(upload_to='pic')),
                ('voice_recorder', models.FileField(blank=True, null=True, upload_to='voice_recording')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktdc_app.employee')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_grievances', to='ktdc_app.hod')),
            ],
        ),
    ]
