# Generated by Django 4.0.1 on 2023-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0005_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
