# Generated by Django 4.0.1 on 2023-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0006_grievance_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
