# Generated by Django 4.0.1 on 2023-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0007_grievance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='message_reply_time',
            field=models.DateTimeField(null=True),
        ),
    ]
