# Generated by Django 4.0.1 on 2023-03-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0008_grievance_message_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_grievances', to='ktdc_app.hod'),
        ),
    ]
