# Generated by Django 4.0.1 on 2023-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0009_grievance_forwarded_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
