# Generated by Django 4.0.1 on 2023-04-16 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0010_grievance_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('aadhar_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$', 'Enter as shown in your aadhar card')])),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('email_id', models.CharField(max_length=100, unique=True)),
                ('mobile_no', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=250)),
            ],
        ),
    ]
