# Generated by Django 4.0.1 on 2023-04-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktdc_app', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
